Repository UBC-MDS/DSCI-532_2024_20_hotspot, pull requests merged in 2024-04, with the labels that each got.

#16 made simple mvp for dashboard
  data/processed/co2-data.csv
  data/processed/country_codes.json
  notebooks/eda.ipynb
  notebooks/preprocess.ipynb
  src/app.py
  src/assets/favicon.ico
  src/hotspot_plot.py
Labels: feature

#20 deploy the mvp to render.com
  Procfile
  README.md
  requirements.txt
  src/__init__.py
  src/app.py
  src/hotspot_plot.py
Labels: feature

#36 improve code readability and performance
  src/app.py
  src/hotspot_plot.py
Labels: bug

#40 38 fixed graph values, colors, scaling
  src/app.py
  src/hotspot_plot.py
Labels: bug

#43 42 fix world map
  notebooks/eda.ipynb
  src/app.py
  src/hotspot_plot.py
Labels: bug

#47 rearranged file structure
  src/app.py
  src/assets/style.css
  src/callbacks.py
  src/components.py
  src/data.py
Labels: bug, feature

#57 53 milestone 3 reflection
  reports/m3_reflection.md
Labels: documentation

#62 add selected_year as description
  src/app.py
  src/assets/style.css
  src/callbacks.py
  src/components.py
Labels: feature

#68 64 address graph feedback
  src/app.py
  src/assets/style.css
  src/components.py
  src/hotspot_plot.py
Labels: bug, feature

#73 add cache to callback
  .gitignore
  environment.yml
  requirements.txt
  src/app.py
  src/callbacks.py
  src/components.py
Labels: feature

#81 79 add new bar chart for emission per capita
  =4.2.0
  data/processed/co2-data.csv
  data/processed/co2-data.parquet
  notebooks/eda.ipynb
  notebooks/preprocess.ipynb
  src/app.py
  src/callbacks.py
  src/components.py
  src/hotspot_plot.py
Labels: feature
